Feature/modal improvements
serudda/side-ui pull request #100
Opened 2024-03-23 20:00 UTC by serudda

## Changes Made 🎉

- [x] feat: added new feature to improve user experience
- [ ] fix: corrected a bug with login functionality
- [x] refactor: improved code readability and organization
- [ ] docs: updated README with new instructions
- [ ] chore: updated dependencies and configuration files

### Describe Changes

- [FullScreen improvement on the Modal component](https://github.com/serudda/side-ui/commit/3976b7436c42cbad05980de225de7839e115c590)

## Visuals (Optional)

<img width="1680" alt="image" src="https://github.com/serudda/side-ui/assets/10075532/98f930c9-dc8b-483e-93a6-7d6b6a121a6e">

## Checklist ✅

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2024-03-24 17:20 UTC, Zyruks requested changes
Muy buen PR, cositas pequeñas que ver.

2024-03-24 17:20 UTC, Zyruks commented on src/components/Overlays/Modals/ModalRoot.tsx
> +    const BASE_MODAL_SIZE_GAP = 'calc(100% - 3.5rem)';
¿Este `BASE_MODAL_SIZE_GAP` que hace? 
 
 Lo modifico a 5rem, 10,rem y no veo que cambie nada.
 
 Y si buscamos el 70% de del screen height porque no usar `h-[70svh]`, Ya que con el calc asumimos un height predefinido y cada pantalla tendrá diferentes valores.

2024-03-24 17:20 UTC, Zyruks commented on src/components/Overlays/Modals/ModalRoot.tsx
> +    const BASE_MODAL_SIZE_GAP = 'calc(100% - 3.5rem)';
```suggestion
    const BASE_MODAL_SIZE_GAP = '70svh';
```

2024-03-26 15:01 UTC, serudda commented on src/components/Overlays/Modals/ModalRoot.tsx
> +    const BASE_MODAL_SIZE_GAP = 'calc(100% - 3.5rem)';
Don Zyruks fue un hack que implementamos en EVA para que el Modal tuviera un scroll interno... pruebo lo que me dices, y te comparto.

2024-03-26 15:14 UTC, merged