[SU-54] ✨ implement SlideOver component
serudda/side-ui pull request #64
Opened 2023-09-05 16:45 UTC by Zyruks

## Changes Made 🎉

- [X] feat: added a new `SlideOver` Component

### Describe Changes

- Created a new component `SlideOver` that provides a slide-out panel for focused user interactions.
- Added props for customizing its appearance, alignment, and content.
- Included stories in `SlideOver.stories.tsx` to showcase its usage with different scenarios.
- Updated `index.ts` barrel file to export `SlideOver` component.

## Related Issue(s)

- #54 

## Visuals (Optional)

![firefox_fCB72WltON](https://github.com/serudda/side-ui/assets/14036522/3ba0fc22-cdf5-4e20-8ed3-8880f07196da)

## Checklist ✅

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2023-09-10 16:56 UTC, serudda commented on src/components/SlideOver/SlideOver.tsx
> +  [SlideOverWidth.base]: 'sm:min-w-[28rem]',
Don Zyruk, no tenemos una class de TailwindCSS que se aproxime?

2023-09-10 16:56 UTC, serudda commented on src/components/SlideOver/SlideOver.tsx
> +      'flex-row-reverse': isTitleRightAligned,
Cual es el fin de esto?

2023-09-10 16:57 UTC, serudda requested changes
Revisar comments

2023-09-10 16:59 UTC, Zyruks commented on src/components/SlideOver/SlideOver.tsx
> +      'flex-row-reverse': isTitleRightAligned,
El `flex-row-reverse` es para cambiar el orden de los elementos

2023-09-12 01:45 UTC, Zyruks commented on src/components/SlideOver/SlideOver.tsx
> +  [SlideOverWidth.base]: 'sm:min-w-[28rem]',
El maximo es 96 para min-w

2023-09-12 01:50 UTC, Zyruks commented on src/components/SlideOver/SlideOver.tsx
> +  [SlideOverWidth.base]: 'sm:min-w-[28rem]',
![image](https://github.com/serudda/side-ui/assets/14036522/461137b2-8de6-4dff-ba56-11a059e1322c)

Entre 96 y 100 no tenemos mucha diferencia y el proximo es 128 que es super grande

No tiene un medio entre 100 y 128

2023-09-13 13:44 UTC, serudda commented on src/components/SlideOver/SlideOver.tsx
> +  [SlideOverWidth.base]: 'sm:min-w-[28rem]',
y cuantos pixeles necesitas? son muchos?

2023-09-13 13:44 UTC, serudda commented on src/components/SlideOver/SlideOver.tsx
> +      'flex-row-reverse': isTitleRightAligned,
y por que necesitas cambiar el orden de los elementos?

2023-09-13 13:46 UTC, serudda requested changes

2023-09-13 13:46 UTC, serudda commented on src/components/SlideOver/SlideOver.tsx
> +  isRightAligned?: boolean;
creo que es mas diciente: **isInverted**

2023-09-13 13:46 UTC, serudda commented on src/components/SlideOver/SlideOver.tsx
> +   * The width size of the SlideOver ('xs', 'sm', 'base', 'xl').
```suggestion
   * The width size of the SlideOver
```

2023-09-13 13:46 UTC, serudda commented on src/components/SlideOver/SlideOver.tsx
> +  isTitleRightAligned = true,
Confunden estas props, no dan contexto por si solas.

2024-01-10 06:08 UTC, closed without merging