[SU-70] fix alias ts
serudda/side-ui pull request #71
Opened 2023-09-11 18:11 UTC by Zyruks

## Changes Made 🎉

- [x] build: update vite config 
- [x] chore: update alias

### Describe Changes

Update typescript routes from @/* to
 ``` 
  "@common": ["./src/common"],
  "@components": ["./src/components"],
  "@contexts": ["./src/contexts"],
  "@hooks": ["./src/hooks"],
  "@storybook": ["./src/storybook"]
```
Updated components routes
## Related Issue(s)

- #70 

## Checklist ✅

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2023-09-11 21:24 UTC, serudda requested changes

2023-09-11 21:24 UTC, serudda commented on src/components/Icon/Icon.stories.ts
> +import { parseIconOptions } from '@storybook';
Este te funciona? por que **@storybook** hace referencia a la lib en node_modules... nuestro **@/storybook** hace referencia a una carpeta llamada asi, donde dentro tiene el utils... se podria renombrar esa carpeta para que no generara confusion.

2023-09-11 21:24 UTC, serudda commented on src/components/Icon/Icon.stories.ts
> +import { parseIconOptions } from '@storybook';
Para probar si te funciona, este parseIconOptions, lo unico que hace es que en storybook vas a este componente, y cuando quieras cambiare una prop que requiere listarte todos los icons del catalogo, se muestra el nombre bien bonito... sino te funciona, en vez de los nombres bonitos, veras una chorrera de paths y svg inlegibles.

2023-09-11 21:24 UTC, serudda commented on src/components/Inputs/TextInput/TextInput.stories.tsx
> +import { parseIconOptions } from '@storybook';
Lo mismo aqui:

Este te funciona? por que @storybook hace referencia a la lib en node_modules... nuestro @/storybook hace referencia a una carpeta llamada asi, donde dentro tiene el utils... se podria renombrar esa carpeta para que no generara confusion.

2023-09-11 21:24 UTC, serudda commented on tsconfig.json
> +      "@storybook": ["./src/storybook"]
Depronto renombrar esta carpeta para que no se confuda con la lib en node_modules

2023-09-12 01:42 UTC, Zyruks commented on src/components/Icon/Icon.stories.ts
> +import { parseIconOptions } from '@storybook';
Funciona, pero se cambió a @storybookConfig para no generar confusión en el futuro

2023-09-12 01:42 UTC, Zyruks commented on src/components/Inputs/TextInput/TextInput.stories.tsx
> +import { parseIconOptions } from '@storybook';
Done!

2023-09-12 01:51 UTC, serudda approved these changes

2023-09-12 01:51 UTC, merged