[SU-07] copy button component
serudda/side-ui pull request #8
Opened 2023-06-02 07:09 UTC by Zyruks

## Changes Made 🎉

- [X] feat(icons): 🍱 update icon component with a copy icon
- [X] feat(buttons): ✨ Add Copy Button component and related files

### Describe Changes

The pull request adds a new Copy Button component to the side-ui component library. The Copy Button component allows users to easily copy text content to the clipboard, enhancing the user experience. It includes the Copy.tsx file with the component implementation, the Copy.stories.ts file for storybook documentation, and an update to the index.ts file to export the Copy Button component.

## Related Issue(s)

- #7 

## Visuals (Optional)

![firefox_xk8TiQWWRL](https://github.com/serudda/side-ui/assets/14036522/03cbc63d-9301-40c5-b5b3-c35f0d8ea0d2)

## Checklist ✅

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-06-02 07:11 UTC, Zyruks commented on src/components/Buttons/Copy/Copy.stories.ts
> +    target: document.createElement('div'),
@serudda Deje un TODO porque no sé qué poner para hacer un target en storybook funcional

Deje ese document.createElement porque así no gritaba el TS, pero necesito una ayuda para resolver ese problema.

2023-06-02 15:37 UTC, serudda requested changes

2023-06-02 15:37 UTC, serudda commented on src/components/Buttons/Copy/Copy.tsx
> +  invert?: boolean;
Con lo anterior te evitas declarar cada prop nuevamente aqui... solo declaras las que ButtonProps no tenga

2023-06-02 15:37 UTC, serudda commented on src/components/Buttons/Copy/Copy.tsx
> +}: CopyBtnProps) => {
```suggestion
export const CopyBtn = ({
  className,
  target,
  size = ButtonSize.base,
  invert = true,
  variant = ButtonVariant.ghost,
  isIconSolid = false,
  isDisabled = false,
  ...restOfProps
}: CopyBtnProps) => {
```

Este ejemplo no vas a encontrar en TextInput... ahi te muestra como extende de Input, y hace el **...restOfProps**

Si no entiendes algo me escribes

2023-06-02 15:37 UTC, serudda commented on src/components/Buttons/Copy/Copy.tsx
> +    const text = target?.textContent;
creo que seria bueno tener varios ejemplos en Storybook mostrando como se usa... ejemplo: uno sacante el texto de un **div**, otro sacando el texto de un **Textarea**.... y uno que saque el texto de un elemento anidado... para ver si lo saca correctamente.

2023-06-02 15:37 UTC, serudda commented on src/components/Buttons/Copy/Copy.tsx
> +    <Tooltip text={tooltipText}>
Que pasa si quiero que el componente en vez de mostrar un icono, me muestre la palabra: **Copiar**? 
tendriamos que hacer refactor de esto no?

2023-06-02 21:05 UTC, Zyruks commented on src/components/Buttons/Copy/Copy.tsx
> +  invert?: boolean;
Super!!! me gusta.

2023-06-04 02:05 UTC, Zyruks commented on src/components/Icon/Icon.tsx
> +  copy = "M10 8V7c0-1 0-1.4.3-1.7.3-.3.8-.3 1.7-.3h5c1 0 1.4 0 1.7.3.3.3.3.8.3 1.7v5c0 1 0 1.4-.3 1.7-.3.3-.8.3-1.7.3h-1m-9 5h5c1 0 1.4 0 1.7-.3.3-.3.3-.8.3-1.7v-5c0-1 0-1.4-.3-1.7-.3-.3-.8-.3-1.7-.3
Listo Modificado a heroicons.

2023-06-04 02:06 UTC, Zyruks commented on src/components/Buttons/Copy/Copy.tsx
> +import { Button, ButtonSize, ButtonVariant, IconCatalog, Tooltip } from '~/components';
Interesante, ya hice el cambio ;)

2023-06-04 02:06 UTC, Zyruks commented on src/components/Buttons/Copy/Copy.tsx
> +interface CopyBtnProps {
Done

2023-06-04 02:08 UTC, Zyruks commented on src/components/Icon/Icon.tsx
> +  copy = "M10 8V7c0-1 0-1.4.3-1.7.3-.3.8-.3 1.7-.3h5c1 0 1.4 0 1.7.3.3.3.3.8.3 1.7v5c0 1 0 1.4-.3 1.7-.3.3-.8.3-1.7.3h-1m-9 5h5c1 0 1.4 0 1.7-.3.3-.3.3-.8.3-1.7v-5c0-1 0-1.4-.3-1.7-.3-.3-.8-.3-1.7-.3
Vi que actualizo el icon component agregando el clipboard. 

Ya lo saco de este PR.

2023-06-05 03:54 UTC, Zyruks commented
Termine los cambios @serudda, tengo una dudas con el storybook no pude desactivar el htmlType y el children del storybook.

Tampoco pude darle el satisfied para el storybook me da problema con el target pero no encontre una solucion. Igual le echo un ojo mañana

![image](https://github.com/serudda/side-ui/assets/14036522/4eb68a39-8a80-4474-ae12-1708bdbafc61)

## Le dejo el preview
![firefox_R2MKCq3ABy](https://github.com/serudda/side-ui/assets/14036522/583d97f6-92d7-4157-b4bb-d99e30175aec)

2023-06-11 17:04 UTC, serudda commented
This POR was implemented in another branch.

2023-06-11 17:04 UTC, closed without merging