Feature / Add breadcrumb component
serudda/side-ui pull request #94
Opened 2024-02-17 19:51 UTC by Zyruks

## Changes Made 🎉

- [x] feat(breadcrumb): ✨[add breadcrumb component](https://github.com/serudda/side-ui/commit/c0af871c9f70cbc62afcf396135ac5eece6c0275)
- [x] feat(story): ✨[add breadcrumb story](https://github.com/serudda/side-ui/commit/6481679e031850264b5106ea1f9da8cbd74895da)
- [x] fix(tailwind): 🐛[darkMode is bug without adding darkMode in config file](https://github.com/serudda/side-ui/commit/4a7e59f08a51eb1fda3c4e983ffa9c2d9bd2ad85)

### Describe Changes

This PR introduces the `Breadcrumb` component, aiming to improve the user navigation experience by providing a clear path back to the starting or entry point of a website or application. The addition of a Storybook story for the `Breadcrumb` component allows developers and designers to interact with the component and understand its functionality and customization options. Furthermore, a minor UI enhancement was made by updating the hover color for better visibility and interaction. Lastly, a critical fix was applied to the Tailwind configuration to support dark mode properly, ensuring a consistent and user-friendly theme across the application.

## Visuals (Optional)

https://github.com/serudda/side-ui/assets/14036522/c17115ce-7b5e-49cc-a844-7ff7802b2422

## Checklist ✅

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2024-02-18 00:02 UTC, serudda requested changes

2024-02-18 00:02 UTC, serudda commented on src/components/Breadcrumbs/utils/helper.tsx
> +interface ProcessBreadcrumbItemProps {
Por que si es un util, lo defines como un component?

2024-02-18 00:02 UTC, serudda commented on tailwind.config.js
> +          50: '#EFF8FF',
Estos colores de donde salieron?

2024-02-19 12:03 UTC, Zyruks commented on src/components/Breadcrumbs/Breadcrumb.stories.tsx
> +              <Breadcrumb {...args} spacing={spacing}>
Spacing es el gap entre elementos.

¿Debería tener otro nombre?

![image](https://github.com/serudda/side-ui/assets/14036522/a26dcd7a-c707-46a5-883a-627f3e73af19)

2024-02-19 12:03 UTC, Zyruks commented on src/components/Breadcrumbs/Breadcrumb.stories.tsx
> +      <Breadcrumb {...args} isCollapse={true} itemsBeforeCollapse={1} itemsAfterCollapse={2}>
Done!

2024-02-19 12:04 UTC, Zyruks commented on src/components/Breadcrumbs/Breadcrumb.stories.tsx
> +      <Breadcrumb {...args} isCollapse={true} itemsBeforeCollapse={2} itemsAfterCollapse={1}>
Done!

2024-02-19 12:04 UTC, Zyruks commented on src/components/Breadcrumbs/Breadcrumb.stories.tsx
> +      <Breadcrumb {...args} isCollapse={true} collapseMode={CollapseMode.spread}>
Done!

2024-02-19 12:04 UTC, Zyruks commented on src/components/Breadcrumbs/Breadcrumb.stories.tsx
> +      <Breadcrumb {...args} isCollapse={true} collapseMode={CollapseMode.dropdown}>
Done!

2024-02-19 12:04 UTC, Zyruks commented on src/components/Breadcrumbs/Breadcrumb.tsx
> +export enum BreadcrumbSpacing {
Spacing es el gap entre elementos.

¿Debería tener otro nombre?

![image](https://github.com/serudda/side-ui/assets/14036522/a26dcd7a-c707-46a5-883a-627f3e73af19)

2024-02-19 12:05 UTC, Zyruks commented on src/components/Breadcrumbs/BreadcrumbCollapsed/CollapsedSpread.tsx
> +import React, { ReactNode } from 'react';
Done!

2024-02-19 12:06 UTC, Zyruks commented on tailwind.config.js
> +          50: '#EFF8FF',
De un archivo en el root `tailwind-presets/storybook-preset.js`

![image](https://github.com/serudda/side-ui/assets/14036522/e113870a-eba9-4468-bc49-266f30f490be)

2024-02-19 12:43 UTC, Zyruks commented on src/components/Breadcrumbs/Breadcrumb.tsx
> +  );
Done!

2024-02-19 12:53 UTC, Zyruks commented on src/components/Breadcrumbs/BreadcrumbCollapsed/CollapsedSpread.tsx
> +      <React.Fragment key={index}>
Done!

2024-02-19 13:41 UTC, Zyruks commented on src/components/Breadcrumbs/Breadcrumb.tsx
> +    if (
Done!

2024-02-19 16:59 UTC, Zyruks commented on src/components/Breadcrumbs/Breadcrumb.tsx
> +  const startItems = childrenBeforeCollapse.map((item) =>
Done!

2024-02-19 16:59 UTC, Zyruks commented on src/components/Breadcrumbs/Breadcrumb.tsx
> +  const collapseItems = collapsedChildren.map((item) =>
Done!

2024-02-19 16:59 UTC, Zyruks commented on src/components/Breadcrumbs/Breadcrumb.tsx
> +  const endItems = childrenAfterCollapse.map((item) =>
Done!

2024-02-19 17:00 UTC, Zyruks commented on src/components/Breadcrumbs/utils/helper.tsx
> +interface ProcessBreadcrumbItemProps {
Done!

se movio a un customHook `useBreadcrumb`

2024-02-20 14:01 UTC, serudda requested changes

2024-02-20 14:01 UTC, serudda commented on src/hooks/useBreadcrumb/useBreadcrumb.tsx
> +            <span key="first-separator" className={classes.separator}>
No Don Zyruks... hay una confusion aqui... este "custom hook" en realidad te esta devolviendo un componente. Y estoy viendo que te esta devolviendo un "Breadcrumb" (1 solo, multiples son "Breadcrumbs")...

Asi que lo mejor es que se aun component local llamado `<Breadcrumb />`

2024-02-20 14:08 UTC, Zyruks commented on src/components/Breadcrumbs/Breadcrumb.stories.tsx
> +  title: 'UI Components/Breadcrumb',
Done!

2024-02-20 14:08 UTC, Zyruks commented on src/components/Breadcrumbs/Breadcrumb.stories.tsx
> +      <Breadcrumb {...args}>
Done!

2024-02-20 14:11 UTC, Zyruks commented on src/components/Breadcrumbs/Breadcrumb.tsx
> +}: BreadcrumbProps) => {
Done!

2024-02-20 14:11 UTC, Zyruks commented on src/components/Breadcrumbs/Breadcrumb.tsx
> +export const Breadcrumb = ({
Done!

2024-02-20 15:53 UTC, Zyruks commented on src/hooks/useBreadcrumb/useBreadcrumb.tsx
> +            <span key="first-separator" className={classes.separator}>
Ahora vive dentro de `Breadcrumbs` como function `parseBreadcrumb`

2024-02-20 15:53 UTC, Zyruks commented on src/components/Breadcrumbs/Breadcrumb.tsx
> +}: BreadcrumbProps) => {
Done!

2024-02-21 00:13 UTC, serudda approved these changes

2024-02-21 00:13 UTC, merged